name: "Upload artifact with current job ID appended"
description: "Upload artifact with current job ID appended to the end"

inputs:
  path:
    description: "Paths to pass to upload-artifact and upload"
    required: true
  prefix:
    description: "Artifact name prefix"
    default: "artifact_"
  run-attempt:
    description: "Run attempt for workflow"
    default: "${{ github.run_attempt || 1 }}"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      id: get-current-job-id
      env:
        JOB_NAME: "${{ github.job }}"
        GITHUB_RUN_ATTEMPT: "${{ inputs.run-attempt }}"
      with:
        result-encoding: string
        retries: 3
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          const runId = context.runId;
          console.log(context.runAttempt);

          const { JOB_NAME, GITHUB_RUN_ATTEMPT } = process.env;
          const runAttempt = GITHUB_RUN_ATTEMPT;

          const jobs = await github.
            paginate(
              "GET /repos/{owner}/{repo}/actions/runs/{runId}/attempts/{runAttempt}/jobs",
              { owner, repo, runId, runAttempt },
          );

          const matchingJobs = jobs.filter(job => job.name == JOB_NAME);

          if (matchingJobs.length !== 1) {
            throw new Error(`Expected exactly one matching job, but found ${matchingJobs.length}`);
          }

          return matchingJobs[0].id;
    - name: Get artifact name result
      shell: bash
      run: echo "${{ inputs.prefix }}${{ steps.get-current-job-id.outputs.result }}"
    - uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.prefix }}${{ steps.get-current-job-id.outputs.result }}"
        path: ${{ inputs.path }}
