name: "Release Docs: package the docs and publish to Docs the repo"

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  # Note that people may spam the post-commit pipeline on their branch, and
  # we have this docs pipeline in the post-commit pipeline, then people
  # would have to wait until the previous one fully completes. That may be
  # ok because each post-commit pipeline definitely takes more than 30 min
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  package-push-docs:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        arch: [grayskull]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      DOCS_VERSION: latest
      ARCH_NAME: ${{ matrix.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    environment: dev
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: false
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ubuntu-20.04
      - uses: ./.github/actions/install-metal-dev-deps
        with:
          os: ubuntu-20.04
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.arch }}
      - name: Extract files
        run: tar -xvf ttm_${{ matrix.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - name: Build Docs
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          doxygen
      - name: Package TT-Metalium Docs
        run: |
          mkdir tt-metalium
          cp -Lr docs/doxygen_build tt-metalium
          cp -Lr docs/source/tt-metalium/* tt-metalium
          rm tt-metalium/conf.py  # Do not change conf.py
          GITHUB_USER=tenstorrent-github-bot
          git config --global user.email "tenstorrent-github-bot@tenstorrent.com"
          git config --global user.name "tenstorrent-github-bot"
          echo "About to clone"
          git clone https://${GITHUB_USER}:${{ secrets.TTBOT_DOCS_ACCESS }}@github.com/tenstorrent/docs-test.git
          git remote set-url origin https://${GITHUB_USER}::${{ secrets.TTBOT_DOCS_ACCESS }}@github.com/tenstorrent/docs-test.git
          echo "Fetching origin"
          git fetch origin
          git checkout main
          echo "Preparing assets"
          cp -r tt-metalium/* docs-test/tt-metalium
          echo "Adding version tags"
          python update_tags.py tt-metalium $DOCS_VERSION
          git add .
          git commit -m "update metalium docs from pipeline CI_PIPELINE_ID with tag CI_COMMIT_TAG"
          git tag -a $DOCS_VERSION -m "metalium documentation version CI_COMMIT_TAG"
          echo "Pushing the new docs"
          git push && git push --tags
      - name: Upload tt-metalium docs
        uses: actions/upload-artifact@v4
        with:
          name: tt-metalium-docs
          path: |
            tt-metalium
      - name: Package TT-NN Docs
        run: |
          mkdir ttnn-docs
          cp -Lr docs/doxygen_build ttnn-docs
          cp -Lr docs/source/ttnn/* ttnn-docs
          rm ttnn-docs/conf.py  # Do not change conf.py
          GITHUB_USER=tenstorrent-github-bot
          git config --global user.email "${GITHUB_USER}@tenstorrent.com"
          git config --global user.name "${GITHUB_USER}"
          git clone https://${GITHUB_USER}:${{ secrets.TTBOT_DOCS_ACCESS }}@github.com/tenstorrent/docs-test.git
          git remote set-url origin https://${GITHUB_USER}:${{ secrets.TTBOT_DOCS_ACCESS }}@github.com/tenstorrent/docs-test.git
          git fetch origin
          git checkout main
          cp -r ttnn-docs/* docs-test/ttnn
          python update_tags.py ttnn $DOCS_VERSION
          git add .
          git commit -m "update ttnn docs from pipeline CI_PIPELINE_ID with tag CI_COMMIT_TAG"
          git tag -a $DOCS_VERSION -m "ttnn documentation version CI_COMMIT_TAG"
          git push && git push --tags
      - name: Upload ttnn-docs
        uses: actions/upload-artifact@v4
        with:
          name: ttnn-docs
          path: |
            ttnn-docs
      - name: Push docs to Docs repo for publishing
        run: |
          echo "List files"
